favicon: null
name: prixgeorgesnicole
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.3125
  brandStrength: 0.6875
  rhythmicContrast: 0.75
  brandColors:
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
  lightness: 0.625
typography_spectrum: 0.36042
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.9784946
analytics:
  twitter: null
  google: null
  facebook: null
